version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=documents_db
      - POSTGRES_USER=service_account
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U service_account -d bank_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: DocumentProcessingService/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/documents_db
      - SPRING_DATASOURCE_USERNAME=service_account
      - SPRING_DATASOURCE_PASSWORD=password
      - WORKERS_SUBMIT_NAME=SubmitWorker
      - WORKERS_SUBMIT_INITIAL_DELAY=20000
      - WORKERS_SUBMIT_FIXED_DELAY=40000
      - WORKERS_APPROVE_NAME=ApprovalWorker
      - WORKERS_APPROVE_INITIAL_DELAY=20000
      - WORKERS_APPROVE_FIXED_DELAY=40000
      - SCHEDULING_POOL_SIZE=2

volumes:
  pgdata: