server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.yaml

workers:
    batch:
      size: 15
    submit:
      name: ${WORKERS_SUBMIT_NAME}
      initialDelay: ${WORKERS_SUBMIT_INITIAL_DELAY}
      fixedDelay: ${WORKERS_SUBMIT_FIXED_DELAY}
    approve:
      name: ${WORKERS_APPROVE_NAME}
      initialDelay: ${WORKERS_APPROVE_INITIAL_DELAY}
      fixedDelay: ${WORKERS_APPROVE_FIXED_DELAY}

scheduling:
  pool:
    size: ${SCHEDULING_POOL_SIZE}